name: 'Telegram Notification Gate'
description: 'Send Github events as notification to Telegram messenger'
author: 'Ethyaan <https://github.com/ethyaan>'

inputs:
  token:
    description: 'Telegram bot Token'
    required: true
  to:
    description: 'Chat id, group or chanel'
    required: true
  thread_id:
    description: 'id of thread or topic to send inside'
  disable_web_page_preview:
    description: 'disables link previews for links in this message'
  disable_notification:
    description: 'disables notifications for this message, supports sending a message without notification.'
  status: 
    description: 'Job status'
    default: ${{ job.status }}
  event: 
    description: 'Event triggered action'
    default: ${{ github.event_name }}
  actor: 
    description: 'Actor who did the action'
    default: ${{ github.actor }}
  repository: 
    description: 'github repository name'
    default: ${{ github.repository }}
  workflow: 
    description: 'github workflow name'
    default: ${{ github.workflow }}

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'message-square'
  color: 'green'